name: Eval Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: eval-smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    name: Simulator Smoke
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run evaluation smoke
        run: npm run eval:ci
      - name: List results
        run: ls -l eval/results || true
      - name: Upload latest summary
        if: ${{ hashFiles('eval/results/latest.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: eval-latest-json
          path: eval/results/latest.json
          retention-days: 7
